<a href="https://colab.research.google.com/github/bruk-lemma/Tensor-Flow-Deep-Learning/blob/main/00_TensorFlow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#create a tensor with tf.constant
import tensorflow as tf;
print(tf.__version__)
scalar=tf.constant(8)
scalar


2.8.2


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [7]:
#check the number of dimensions of a tensor  ndim stands for number of dimensions.
scalar.ndim

0

In [8]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
#check the dimensions of our vector
vector.ndim

1

In [10]:
#create a matrix (has more than one dimension)
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [13]:
#createa another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]], dtype=tf.float16) 
#specify the data type with dtype float 16 which is known as 32 bir precision.
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
another_matrix.ndim

2

In [15]:
bigger_matrix=tf.constant([[1.,2.,9.],
                           [3.,4.,8.],
                           [5.,6.,7.]],dtype=tf.float16)
bigger_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 9.],
       [3., 4., 8.],
       [5., 6., 7.]], dtype=float16)>

In [16]:
bigger_matrix.ndim


2

In [19]:
#lets create a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6]],
                   [[7,8,9],
                    [10,11,12]],
                   [[13,14,15],
                    [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [21]:
tensor.ndim


3

In [ ]:
#what we have created so far

# Scalar:a single number
# Vector: a number with direction (eg: wind speed and direction)
# Matrix: a 2-dimentional array of numbers
# Tensor: an n-dimensional array of numbers (when n can be any number, a 0 dimensional tensor is a scalar, a 1-dimensional tensor  is vector) 