<a href="https://colab.research.google.com/github/bruk-lemma/Tensor-Flow-Deep-Learning/blob/main/02_TensorFlow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#create a tensor with tf.constant
import tensorflow as tf;
print(tf.__version__)
scalar=tf.constant(8)
scalar


In [4]:
import  tensorflow as tf

In [ ]:
#check the number of dimensions of a tensor  ndim stands for number of dimensions.
scalar.ndim

0

In [5]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimensions of our vector
vector.ndim

1

In [ ]:
#create a matrix (has more than one dimension)
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#createa another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]], dtype=tf.float16) 
#specify the data type with dtype float 16 which is known as 32 bir precision.
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
bigger_matrix=tf.constant([[1.,2.,9.],
                           [3.,4.,8.],
                           [5.,6.,7.]],dtype=tf.float16)
bigger_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 9.],
       [3., 4., 8.],
       [5., 6., 7.]], dtype=float16)>

In [ ]:
bigger_matrix.ndim


2

In [ ]:
#lets create a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6]],
                   [[7,8,9],
                    [10,11,12]],
                   [[13,14,15],
                    [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim


3

In [ ]:
#what we have created so far

# Scalar:a single number
# Vector: a number with direction (eg: wind speed and direction)
# Matrix: a 2-dimentional array of numbers
# Tensor: an n-dimensional array of numbers (when n can be any number, a 0 dimensional tensor is a scalar, a 1-dimensional tensor  is vector) 

**.Creating Tensors with tf.Varibles**

In [ ]:
#Create the same tensor with tf.Variables() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#lets try to change the element in our changeable tensor
changeable_tensor[0]
changeable_tensor[0].assign(8)
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
#lets try to change the unchangeable_tensor created using tf.constant()
unchangeable_tensor[0]
unchangeable_tensor[0].assign(9)
unchangeable_tensor[0]

AttributeError: ignored

**Creating Random Tensors**
random tensors are tensors of arbitrary size with random random numbers.

In [ ]:
from tensorflow._api.v2 import random
#create two but the same random tensors.
random_1=tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))


#Are they eqaul?
random_1,random_2,random_1==random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
#shuffle a tensor (valuable for when you want to shuffle your data so the inherent order does not effect learning)
not_shuffled=tf.constant([[10,7],[3,4],[7,8]])
#shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7,  8],
       [ 3,  4]], dtype=int32)>

In [ ]:
#shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 7,  8]], dtype=int32)>

In [ ]:
# creating tensors and shuffle
# in order to make our shuffled tensors to have the same order evry time 
# we should use the global random level and operrational level seed.
tf.random.set_seed(42) # configuring seed in two places in the global and operational level seed.
my_shuffle=tf.constant([[1,2],[3,4],[5,6],[7,8]])#shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)
tf.random.shuffle(my_shuffle,seed=42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [7, 8],
       [5, 6]], dtype=int32)>

In [ ]:
#other ways to make tensors.

#create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensor of all zeros
tf.zeros([4,5])


<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

**Turn Numpy into tensors.**
the main difference between Numpy and tensorflow tensors is that tensors can be run on GPU much faster.

In [ ]:
# you can also turn Numpy arrays into tensors.
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32) #create a Numpy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A)
B=tf.constant(A,shape=(2,3,4))
A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

**Getting information from tensors**
when dealing with tensors you probably want to be aware of the following attributes:

* Shape
* Rank
* Axis or dimention
* Size   



In [7]:
#create a rank 4 tensor (4 dimensions)
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_3_tensor=tf.ones(shape=[3,2,2,2])
rank_3_tensor

<tf.Tensor: shape=(3, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#how size is calculated.
2*3*4*5

120

In [ ]:
#Get Various attributes of our tensor
print("Datatype of evry element :", rank_4_tensor.dtype)
print("number of dimensions (rank) :", rank_4_tensor.ndim)
print("Shape of tensor :",rank_4_tensor.shape)
print("Element along the  0 Axis :",rank_4_tensor.shape[0])
print("Element Along the last Axis :",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor :",tf.size(rank_4_tensor))
print("Total number of elements in our tensor :",tf.size(rank_4_tensor).numpy())

Datatype of evry element : <dtype: 'float32'>
number of dimensions (rank) : 4
Shape of tensor : (2, 3, 4, 5)
Element along the  0 Axis : 2
Element Along the last Axis : 5
Total number of elements in our tensor : tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor : 120


**Indexing Tensors**
tensors can be indexed just like Python lists.

In [8]:
#get the first 2 element of each dimesions
rank_4_tensor[:2,:2,:2,:2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>